Update RagnaR-Kernel-DERPFEST.yml

diff --git a/.github/workflows/RagnaR-Kernel-DERPFEST.yml b/.github/workflows/RagnaR-Kernel-DERPFEST.yml
--- a/.github/workflows/RagnaR-Kernel-DERPFEST.yml
+++ b/.github/workflows/RagnaR-Kernel-DERPFEST.yml
@@ -99,12 +99,12 @@ jobs:
           cp $SUSFS/kernel_patches/include/linux/* \
              $KERNEL_ROOT/include/linux/
 
-          echo "Patching KernelSU…"
+          # echo "Patching KernelSU…"
           # cd $KERNEL_ROOT/KernelSU
           # patch -p1 < 10_enable_susfs_for_ksu.patch || {
-            echo "❌ KernelSU patch failed"
-            # exit 1
-          }
+          # echo "❌ KernelSU patch failed"
+          # exit 1
+          # }
 
           echo "Patching kernel main patch…"
           cd $KERNEL_ROOT
